name: Docker-Node-App | Stress Test

on:
  push:
    branches:
      - 'master'
      - 'main'
  schedule:
    - cron: "10 */12 * * *"

jobs:
  stress:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Run k6 Stress Test
        id: dna-stress-test
        uses: k6io/action@v0.1
        with:
          filename: tests/docker-node-app.js

      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()